openapi: 3.0.3
info:
  title: Cars API
  description: A simple API to manage cars and their owners.
  version: 1.0.0

servers:
  - url: https://api.example.com/v1

tags:
  - name: cars
    description: Operations related to cars
  - name: owners
    description: Operations related to car owners

paths:
  /cars:
    get:
      tags:
        - cars
      summary: List all cars
      operationId: listCars
      responses:
        '200':
          description: A list of cars
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'
    post:
      tags:
        - cars
      summary: Add a new car
      operationId: addCar
      requestBody:
        description: Car object to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCar'
      responses:
        '201':
          description: Car successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'

  /cars/{id}:
    get:
      tags:
        - cars
      summary: Get a car by ID
      operationId: getCar
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the car
          schema:
            type: integer
      responses:
        '200':
          description: Car found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
        '404':
          description: Car not found
    delete:
      tags:
        - cars
      summary: Delete a car by ID
      operationId: deleteCar
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the car
          schema:
            type: integer
      responses:
        '204':
          description: Car deleted
        '404':
          description: Car not found

  /owners:
    get:
      tags:
        - owners
      summary: List all car owners
      operationId: listOwners
      responses:
        '200':
          description: A list of owners
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Owner'

components:
  schemas:
    Car:
      type: object
      properties:
        id:
          type: integer
          example: 101
        make:
          type: string
          example: Toyota
        model:
          type: string
          example: Corolla
        year:
          type: integer
          example: 2021
        ownerId:
          type: integer
          example: 55
    NewCar:
      type: object
      required:
        - make
        - model
        - year
      properties:
        make:
          type: string
          example: Tesla
        model:
          type: string
          example: Model 3
        year:
          type: integer
          example: 2022
        ownerId:
          type: integer
          example: 55
    Owner:
      type: object
      properties:
        id:
          type: integer
          example: 55
        name:
          type: string
          example: Alice Johnson
        email:
          type: string
          example: alice@example.com
